# Generated by Django 3.2.9 on 2021-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
